"""Add admin role

Revision ID: 7462e71b9b49
Revises: 8a811eecf514
Create Date: 2026-09-20 17:27:40.819341

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7462e71b9b49"
down_revision: Union[str, Sequence[str], None] = "8a811eecf514"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", type_=sa.String(length=20), existing_type=sa.Enum)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum("advisor", "officer", name="role")
    role_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        "users",
        "role",
        type_=role_enum,
        existing_type=sa.String(length=20),
        postgresql_using="role::role",
    )
    # ### end Alembic commands ###
