"""Add organization model and org ids

Revision ID: 8a811eecf514
Revises: 0db2565ea678
Create Date: 2026-09-19 22:16:12.125441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy



# revision identifiers, used by Alembic.
revision: str = '8a811eecf514'
down_revision: Union[str, Sequence[str], None] = '0db2565ea678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_events', sa.Column('organization_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_foreign_key('fk_audit_events_organization_id_organizations', 'audit_events', 'organizations', ['organization_id'], ['id'])
    op.add_column('documents', sa.Column('organization_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_foreign_key('fk_documents_organization_id_organizations', 'documents', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key('fk_users_organization_id_organizations', 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_users_organization_id_organizations', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_documents_organization_id_organizations', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_column('documents', 'organization_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_audit_events_organization_id_organizations', 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_column('audit_events', 'organization_id')
    op.drop_table('organizations')
    # ### end Alembic commands ###
