"""Add last_seen_at to users

Revision ID: 85b50588e9e9
Revises: 04777d1558a7
Create Date: 2026-09-23 19:05:43.128023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '85b50588e9e9'
down_revision: Union[str, Sequence[str], None] = '04777d1558a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_at')
    # ### end Alembic commands ###
