"""Add document_category to ai_analyses

Revision ID: 0db2565ea678
Revises: 62d81ce52d3e
Create Date: 2026-09-19 15:42:43.829894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy



# revision identifiers, used by Alembic.
revision: str = '0db2565ea678'
down_revision: Union[str, Sequence[str], None] = '62d81ce52d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('document_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_analyses', 'document_category')
    # ### end Alembic commands ###
