"""Initial migration

Revision ID: 86ce437a088c
Revises: 
Create Date: 2026-09-15 15:48:49.319545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ce437a088c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_analyses_document_id_fkey'), 'ai_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analyses', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('flags_analysis_id_fkey'), 'flags', type_='foreignkey')
    op.create_foreign_key(None, 'flags', 'ai_analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pii_mappings_document_id_fkey'), 'pii_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'pii_mappings', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'pii_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('pii_mappings_document_id_fkey'), 'pii_mappings', 'documents', ['document_id'], ['id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.create_foreign_key(op.f('flags_analysis_id_fkey'), 'flags', 'ai_analyses', ['analysis_id'], ['id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ai_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('ai_analyses_document_id_fkey'), 'ai_analyses', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
